sudo: false
cache: pip
language: python
python:
- '3.6'
- '3.5'
- '2.7'
- pypy
env:
- MARSHMALLOW_VERSION="==2.8.0"
- MARSHMALLOW_VERSION=""
install:
- travis_retry pip install -U .
- travis_retry pip install -U -r dev-requirements.txt
- travis_retry pip install -U marshmallow"$MARSHMALLOW_VERSION" --pre
script: invoke test
jobs:
  include:
  - stage: PyPI Release
    if: tag IS present
    python: "3.6"
    env: []
    # Override install and script to no-ops
    install: true
    script: echo "Releasing to PyPI..."
    after_success: true
    deploy:
      provider: pypi
      user: sloria
      on:
        tags: true
      distributions: sdist bdist_wheel
      password:
        secure: XRc9UtQUaE3klaDXhbmz42xYOBXIxybgCuZ4dLi0pnb5kWxMpx/dezKF5Mhky2ikOPn8QKuZnyAYyrxAJd5YgZcqJ3o92SLW5fVlWbRWx7FCv6yRCkB6KacaYreHz/p0yia0/mqB33MJKJLY/q00hy82eXYkfseTkRggOhvgiFXJVD4i+6IcAKpimyoGcrR4DxoixplKDUGdwWahSR82qL3ioYie0alclCbITIz/C8IwMPp3sSdOa9UdF8NW5VXCi0FdBC5R25XY0joDcY+sHNl21iKdAaOGVsHa51xdf59dDPTiAQcD8596Zt7g68dezwdsCe+OAXuId9OA3SiDPwGOBRy2GcIr72dmPOZWAfcMADNXHa5cqQTzZu2Gh9AOKFHj/O7f09ILOlRYkz4hnrndVXL5y5IGIgUUbfUi0nM8K33tsLagV4lfOUiuiiBx2PFCQ8j+1LXHY7vMb81uZVn25wdM46hcfNLckD1dEE19N9OuQPfISXzjy7JFiH4O12LjijhirHbuUbkM5CxKtEFVTgRNq/FySHA/zYwMdo8Jg0wlAwQJbsgnGkbsklqWbZOR5+4ZRj0a5liJ4jTJMMmah7ABwI5uhXDop1bRzxVxxSyqdbTWysVNPwQAMbPjGHEN7Y9R9L7/Gba8qhe4VDWSvFhB7emL4PcAv7ZpFU8=
